apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-rxuy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-pnsm-tenant/appstudio/dc-metro-map-rxuy@sha256:f74b8f93a020660034b76fe83746fae05a5552fdef7cc76a49b1089ebc13948d
        name: my-nodejs
        resources: {}
status: {}
