apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-rxuy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-rxuy
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-rxuy
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-rxuy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-rxuy
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-pnsm-tenant/appstudio/dc-metro-map-rxuy@sha256:f74b8f93a020660034b76fe83746fae05a5552fdef7cc76a49b1089ebc13948d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
